src/Entity/Pin.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\PinRepository;
use App\Entity\Traits\Timestampable;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PinRepository::class)
 * @ORM\Table(name="pins")
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks
 * */
class Pin
{   
    use Timestampable;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank (message="Title can't be blank") 
     * @Assert\Length(min=3)     
   
     */
    private $title;


     /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     * @Assert\Length(min=10)
     */
    private $description;

     
 
    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pins")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;


    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="pin_image", fileNameProperty="imageName")
     * @Assert\Image(maxSize="8M")
     * 
     * @var File|null
     */
    private $imageFile;

    /**
    * @ORM\Column(type="string", length=255, nullable=true)
    */
    private $imageName;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string 
    {
        return $this->title;
    }
    public function setTitle(?string $title): self
    {
        $this->title=$title;
        return $this;
    }

    public function getDescription(): ?string 
    {
        return $this->description;
    }
    public function setDescription(?string $description): self
    {
        $this->description = $description;
        return $this;
    }

    /**
     *  @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setUpdatedAt(new \DateTimeImmutable);
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    
   
     public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use App\Entity\Traits\Timestampable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields="email", message="There is already an account with this email")
 */
class User implements UserInterface
{
    use Timestampable;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please enter your first name")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please enter your last name")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank(message="Please enter your email address")
     * @Assert\Email(message="Please enter a valid email address")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Pin::class, mappedBy="user", orphanRemoval=true)
     */
    private $pins;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function __construct()
    {
        $this->pins = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Pin[]
     */
    public function getPins(): Collection
    {
        return $this->pins;
    }
    
    public function addPin(Pin $pin): self
    {
        if (!$this->pins->contains($pin)) {
            $this->pins[] = $pin;
            $pin->setUser($this);
        }

        return $this;
    }

    public function removePin(Pin $pin): self
    {
        if ($this->pins->contains($pin)) {
            $this->pins->removeElement($pin);
            // set the owning side to null (unless already changed)
            if ($pin->getUser() === $this) {
                $pin->setUser(null);
            }
        }

        return $this;
    }

    public function getFullName(): string
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    public function getGravatarUrl(?int $size = 100)
    {
        return sprintf('https://www.gravatar.com/avatar/%s?s=%d', md5(strtolower(trim($this->getEmail()))), $size);
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Form/PinType.php
<?php

namespace App\Form;

use App\Entity\Pin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class PinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('imageFile', VichImageType::class, [
                'label' => 'Image (JPG or PNG file)',
                'required' => false,
                'allow_delete' => true,
                'download_uri' => false,
                'imagine_pattern' => 'squared_thumbnail_small'
            ])
            ->add('title', TextType::class)
            ->add('description', TextareaType::class)
           
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pin::class,
        ]);
    }
}

src/Controller/PinsController.php
<?php

namespace App\Controller;

use App\Entity\Pin;
use App\Entity\Contact;
use App\Form\ContactType;
use Symfony\Component\Mime\Address;
use App\Form\PinType;
use App\Repository\PinRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bridge\Twig\Mime\WrappedTemplatedEmail;

class PinsController extends AbstractController
{
/**
 * @Route("/", name= "app_home", methods="GET")
 */
public function index(PinRepository $pinRepository): Response
{
    $pins = $pinRepository->findBy([], ['createdAt' => 'DESC']);

    return $this->render('pins/index.html.twig', compact('pins'));
}
    
    /**
     * @Route("/pins/create", name="app_pins_create", methods="GET|POST")
     * @IsGranted("PIN_CREATE")
     */
    public function create(Request $request, EntityManagerInterface $em, UserRepository $userRepo): Response
    {
        $pin = new Pin;

        $form = $this->createForm(PinType::class, $pin);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pin->setUser($this->getUser());
            $em->persist($pin);
            $em->flush();

            $this->addFlash('success', 'Pin successfully created!');

            return $this->redirectToRoute('app_home');
        }

        return $this->render('pins/create.html.twig', [
            'form' => $form->createView()
        ]);
    }
    
    /**
     * @Route("/pins/{id<[0-9]+>}", name= "app_pins_show", methods="GET|POST")
     */
    public function show(Pin $pin, Request $request,EntityManagerInterface $em,MailerInterface $mailer ): Response
    {
        $contact = new Contact();
     
        $form = $this->createForm(ContactType::class, $contact);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            
            $email = (new TemplatedEmail())
            ->from($contact->getEmail())
            ->to(new Address(
                $this->getParameter('app.mail_from_address'),
                $this->getParameter('app.mail_from_name'),
            ))        
            ->subject('demande!')
            ->htmlTemplate('notification/not.html.twig')
            ->context([
                'firstname' => $contact->getFirstName(),
                'lastname' => $contact->getLastName(),
                'mail' => $contact->getEmail(),
                'phone' => $contact->getPhone(),
                'message' => $contact->getMessage(),
                'titreArticle' =>$pin->getTitle()
            ])
            ;

        $mailer->send($email);

            $this->addFlash('success', 'votre message a été bien envoyé!');
            return $this->render('pins/show.html.twig', [
                'contact'=>$contact,
                'pin' => $pin,
                'form' => $form->createView()]
            );            
        }

        return $this->render('pins/show.html.twig', [
            'pin' => $pin,
            'form' => $form->createView()]
        );
    }

    
    
    /**
     * @Route("/pins/{id<[0-9]+>}/edit", name="app_pins_edit", methods={"GET", "PUT"})
     * @IsGranted("PIN_MANAGE", subject="pin")
     */
    public function edit(Request $request, Pin $pin, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(PinType::class, $pin, [
            'method' => 'PUT'
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();

            $this->addFlash('success', 'Pin successfully updated!');

            return $this->redirectToRoute('app_home');
        }

        return $this->render('pins/edit.html.twig', [
            'pin' => $pin,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/pins/{id<[0-9]+>}", name="app_pins_delete", methods="DELETE")
     */
    public function delete(Request $request, Pin $pin, EntityManagerInterface $em): Response
    {
        $this->denyAccessUnlessGranted('PIN_MANAGE', $pin);

        if ($this->isCsrfTokenValid('pin_deletion_' . $pin->getId(), $request->request->get('csrf_token'))) {
            $em->remove($pin);
            $em->flush();

            $this->addFlash('info', 'Pin successfully deleted!');
        }

        return $this->redirectToRoute('app_home');
    }
}

templates/pins/_form.html.twig
 {{form_start(form)}}
            {{form_widget(form)}}
            <input type="submit" value="{{submitButtonText}}"  
            class="btn btn-primary btn-lg btn-block"" formnovalidate >
    {{form_end(form)}}

templates/pins/create.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title %}
new Article
{% endblock %}

{% block body %}
    <div class ="row">
        <div class="col-md-6 mx-auto">
    
            <h1> Upload an article to donate </h1>
            {{include('pins/_form.html.twig', {'submitButtonText':'share to give'})}}
        </div>
    </div>
{% endblock %}			

templates/pins/edit.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'Edit*' ~ pin.title %}


{% block body %}
    <div class ="row">
        <div class="col-md-6 mx-auto">
    
             <h1> Edit {{pin.title}} </h1>
             {{include('pins/_form.html.twig', {'submitButtonText':'Update donation'}) }}
        </div>
    </div>
   
{% endblock %}

templates/pins/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title %}Givin' is caring!{% endblock %}

{% block body %}
   {% if pins|length > 0 %}
        <h1 class="mb-4 text-center text-muted">{{ pluralize(pins|length, 'donation') }}</h1>
        
       {% for row in pins|batch(3) %}
            <div class="row mb-5">
            {% for pin in row %}
                <div class="col-md-4">
                    <article class="pin bg-white rounded shadow">
                        <div class="mw-100 rounded-top overflow-hidden">
                            <a href="{{ path('app_pins_show', {id: pin.id}) }}">
                                <img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('build/images/pas-de-photo.png')) | imagine_filter('squared_thumbnail_medium') }}" alt="{{ pin.title }}" class="w-100" />
                            </a>
                        </div>
                        <h2 class="h5 pl-3 pt-3"><a href="{{ path('app_pins_show', {id: pin.id}) }}" class="text-secondary text-decoration-none">{{ pin.title }}</a></h2>
                        <p class="pl-3 pb-3 text-muted"><small>Submitted by {{ pin.user.fullName }}</small></p>
                    </article>
                </div>
            {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <p class="mt-5 h1 text-center">No pins yet. <a href="{{ path('app_pins_create') }}">Be the first!</a></p>
    {% endif %}
{% endblock %}

templates/pins/show.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title pin.title %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <article class="pin bg-white rounded shadow">
                <div class="mw-100 rounded-top overflow-hidden">
                    <img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('build/images/placeholder.jpg')) | imagine_filter('squared_thumbnail_medium') }}" alt="{{ pin.title }}" class="w-100" />
                </div>

                <div class="p-3">
                    <h1 class="h5 text-secondary">{{ pin.title }}</h1>

                    <p class="text-muted">
                        <small>
                            Submitted 
                            <time datetime="{{ pin.createdAt|date('Y-m-d H:i:s') }}">{{ pin.createdAt|ago }}</time>
                            by {{ pin.user.fullName }}
                        </small>
                    </p>

                    <p class="pt-3 text-break">
                        {{ pin.description }}
                    </p>
                    
                  

                    {% if is_granted('PIN_MANAGE', pin) %}
                    <div class="pt-3">
                        <a href="{{ path('app_pins_edit', {'id': pin.id}) }}" class="btn btn-light">Edit</a>
                        <a href="#" onclick="event.preventDefault(); confirm('Are you sure?') && document.getElementById('js-pin-delete-form').submit();" class="btn btn-light">Delete</a>

                        <form id="js-pin-delete-form" action="{{ path('app_pins_delete', {id: pin.id}) }}" method="post" style="display: none;">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token('pin_deletion_' ~ pin.id) }}">
                            <input type="hidden" name="_method" value="DELETE">
                        </form> 
                    </div>
                    {% else %}
                     <div id= "contactForm" class="mt-4">
                     {{ form_start(form) }}
                        <div class="row">
                            <div class="col">{{form_row(form.firstName)}}</div>
                            <div class="col">{{form_row(form.lastName)}}</div>
                        </div>

                        <div class="row">
                            <div class="col">{{form_row(form.phone)}}</div>
                            <div class="col">{{form_row(form.email)}}</div>
                        </div>

                        {{form_rest(form)}}
                            <div class="form-group">
                                <button class="btn btn-primary">contacter</button>
                            </div>
                        {{ form_end(form) }}
                    {% endif %}
                </div>
            </article>
        </div>
    </div>
{% endblock %}